-- ==============================================================================
-- Bayyinah AI - Supabase Knowledge Base Migration 013: Seed Trusted Sources
-- Honest scientific and license status assignments according to Challenge Governance
-- ==============================================================================

INSERT INTO sources (
    id, name, organization, author, category, description, url, specific_url,
    source_type, scientific_status, license_status, license_reference, allowed_operations,
    indexing_allowed, storage_allowed, excerpt_allowed, link_allowed, translation_allowed, embedding_allowed,
    verification_notes, last_verified_at
) VALUES
(
    '00000000-0000-0000-0000-000000000001',
    'مركز دعوة (Dawa Center)',
    'مركز دعوة',
    'هيئة الباحثين بمركز دعوة',
    'DAWA',
    'منصة رسمية متخصصة في المحتوى الدعوي والرد على الشبهات والأسئلة المتكررة وتأهيل المعرفين بالإسلام.',
    'https://dawa.center',
    'https://dawa.center/about',
    'OFFICIAL_PLATFORM',
    'APPROVED',
    'PENDING',
    'شروط الاستخدام الدعوي غير التجاري',
    '{"SEARCH": true, "DISPLAY_EXCERPT": true, "LINK": true, "INDEX": true}'::jsonb,
    true, false, true, true, false, true,
    'مصدر أساسي ضمن الحزمة العلمية للتحدي (المسار الرابع).',
    now()
),
(
    '00000000-0000-0000-0000-000000000002',
    'موسوعة المحتوى الإسلامي / الجمهرة',
    'موسوعة المحتوى الإسلامي',
    'نخبة من الأكاديميين والمترجمين المتخصصين',
    'DICTIONARY_TRANSLATION',
    'موسوعة معجمية متخصصة لتوثيق المصطلحات الشرعية الإسلامية وترجمتها المعيارية المنضبطة لعدة لغات عالمية.',
    'https://islamic-content.com',
    'https://islamic-content.com/dictionary',
    'ENCYCLOPEDIA',
    'APPROVED',
    'PENDING',
    'رخصة المحتوى الأكاديمي الرقمي',
    '{"SEARCH": true, "DISPLAY_EXCERPT": true, "LINK": true, "INDEX": true, "TRANSLATE": true}'::jsonb,
    true, false, true, true, true, true,
    'المرجع المعتمد لترجمة المصطلحات وضبط المفاهيم الإسلامية باللغات العالمية.',
    now()
),
(
    '00000000-0000-0000-0000-000000000003',
    'قرآنسول / Quranpedia',
    'Quranpedia Project',
    'فريق التوثيق القرآني',
    'QURAN',
    'موسوعة متخصصة في علوم القرآن وتراجم معانيه وموضوعات الآيات وتفسيرها والبحث في متونها.',
    'https://quranpedia.net',
    'https://quranpedia.net/surah',
    'OFFICIAL_PLATFORM',
    'APPROVED',
    'PENDING',
    'رخصة الاستخدام العلمي المفتوح',
    '{"SEARCH": true, "DISPLAY_EXCERPT": true, "LINK": true, "INDEX": true}'::jsonb,
    true, false, true, true, false, true,
    'منصة مرجعية للبحث القرآني ومطابقة الرسم العثماني وموضوعات السور.',
    now()
),
(
    '00000000-0000-0000-0000-000000000004',
    'مؤسسة الدرر السنية (Dorar Net)',
    'مؤسسة الدرر السنية',
    'إشراف الشيخ علوي بن عبد القادر السقاف',
    'HADITH',
    'بوابة إلكترونية موسوعية متخصصة في تخريج الحديث، بيان أحكام الأئمة، التفسير المحرر، الفقه المقارن، والسيرة النبوية.',
    'https://dorar.net',
    'https://dorar.net/hadith',
    'HADITH_DATABASE',
    'APPROVED',
    'PENDING',
    'الاستخدام البحثي والدعوي غير التجاري مع ذكر المصدر',
    '{"SEARCH": true, "DISPLAY_EXCERPT": true, "LINK": true, "INDEX": true}'::jsonb,
    true, false, true, true, false, true,
    'المرجع الرقمي الأول لتخريج الأحاديث وبيان أحكام الأئمة عليها وكشف الأحاديث الضعيفة والموضوعة.',
    now()
),
(
    '00000000-0000-0000-0000-000000000005',
    'المكتبة الشاملة (Shamela)',
    'المكتبة الشاملة',
    'أئمة وعلماء الإسلام عبر التاريخ',
    'SEERAH_HISTORY',
    'أضخم مكتبة رقمية للكتب والمصادر الإسلامية التراثية المطبوعة والمحققة عبر القرون.',
    'https://shamela.ws',
    'https://shamela.ws/privacy',
    'DIGITAL_LIBRARY',
    'APPROVED',
    'PENDING',
    'الملكية العامة ونصوص التراث المحققة',
    '{"SEARCH": true, "DISPLAY_EXCERPT": true, "LINK": true, "INDEX": true}'::jsonb,
    true, false, true, true, false, true,
    'أكبر مستودع رقمي لكتب التراث الإسلامي المطبوعة ومراجع الإسناد الموثقة.',
    now()
),
(
    '00000000-0000-0000-0000-000000000006',
    'مركز دعوة - قسم الرد على الشبهات والأسئلة (ملف 7937)',
    'مركز دعوة',
    'هيئة الباحثين بمركز دعوة',
    'QUESTIONS_DOUBTS',
    'حزمة المواد والملفات المعتمدة للإجابة عن الأسئلة المتكررة والشبهات المعاصرة حول الإسلام ورسالة النبي ﷺ.',
    'https://dawa.center/file/7937',
    'https://dawa.center/file/7937',
    'OFFICIAL_PLATFORM',
    'APPROVED',
    'PENDING',
    'شروط الاستخدام الدعوي غير التجاري',
    '{"SEARCH": true, "DISPLAY_EXCERPT": true, "LINK": true, "INDEX": true}'::jsonb,
    true, false, true, true, false, true,
    'مادة أساسية مصنفة ضمن ملف 7937 بالحزمة العلمية للتحدي.',
    now()
),
(
    '00000000-0000-0000-0000-000000000007',
    'معجم المصطلحات الشرعية - المحتوى الإسلامي',
    'موسوعة المحتوى الإسلامي',
    'لجنة المصطلحات والترجمة الشرعية',
    'DICTIONARY_TRANSLATION',
    'المعجم المعياري للمصطلحات والمفاهيم الإسلامية باللغة العربية والإنجليزية وضوابط استخدامها.',
    'https://islamic-content.com/dictionary',
    'https://islamic-content.com/dictionary',
    'ENCYCLOPEDIA',
    'APPROVED',
    'PENDING',
    'رخصة الاستخدام المعجمي والعلمي',
    '{"SEARCH": true, "DISPLAY_EXCERPT": true, "LINK": true, "INDEX": true, "TRANSLATE": true}'::jsonb,
    true, false, true, true, true, true,
    'المرجع المعجمي الرسمي للمصطلحات وترجمتها المنضبطة.',
    now()
),
(
    '00000000-0000-0000-0000-000000000008',
    'مجمع الملك فهد لطباعة المصحف الشريف',
    'مجمع الملك فهد لطباعة المصحف الشريف بالمدينة المنورة',
    'علماء وقراء الأمة بإشراف المجمع',
    'QURAN',
    'المرجع السيادي المعتمد لنص القرآن الكريم برواية حفص عن عاصم، والترجمات المعتمدة لمعاني الآيات الكريمة.',
    'https://qurancomplex.gov.sa',
    'https://qurancomplex.gov.sa',
    'OFFICIAL_PLATFORM',
    'APPROVED',
    'VERIFIED',
    'وقف الملك فهد لطباعة المصحف الشريف',
    '{"SEARCH": true, "DISPLAY_EXCERPT": true, "LINK": true, "INDEX": true, "STORE": true, "TRANSLATE": true}'::jsonb,
    true, true, true, true, true, true,
    'المرجع الأول لضبط المتن القرآني والرسم العثماني المعتمد.',
    now()
),
(
    '00000000-0000-0000-0000-000000000009',
    'الجامع المسند الصحيح المختصر (صحيح البخاري)',
    'دار التأصيل / المحدثون',
    'الإمام محمد بن إسماعيل البخاري (ت: 256هـ)',
    'HADITH',
    'أصح كتب الحديث النبوي الشريف قاطبة وأوثق ديوان للمتون النبوية الصحيحة المرفوعة.',
    'https://sunnah.com/bukhari',
    'https://sunnah.com/bukhari',
    'HADITH_DATABASE',
    'APPROVED',
    'VERIFIED',
    'الملكية العامة (تراث إسلامي محقق)',
    '{"SEARCH": true, "DISPLAY_EXCERPT": true, "LINK": true, "INDEX": true, "STORE": true, "TRANSLATE": true}'::jsonb,
    true, true, true, true, true, true,
    'مرجع أصول السنة الصحيحة المتفق عليها.',
    now()
),
(
    '00000000-0000-0000-0000-000000000010',
    'المسند الصحيح المختصر (صحيح مسلم)',
    'دار التأصيل / المحدثون',
    'الإمام مسلم بن الحجاج النيسابوري (ت: 261هـ)',
    'HADITH',
    'ثاني أصح دواوين الحديث النبوي الشريف بعد صحيح البخاري.',
    'https://sunnah.com/muslim',
    'https://sunnah.com/muslim',
    'HADITH_DATABASE',
    'APPROVED',
    'VERIFIED',
    'الملكية العامة (تراث إسلامي محقق)',
    '{"SEARCH": true, "DISPLAY_EXCERPT": true, "LINK": true, "INDEX": true, "STORE": true, "TRANSLATE": true}'::jsonb,
    true, true, true, true, true, true,
    'ثاني أصح ديوان في السنة النبوية المطهرة.',
    now()
),
(
    '00000000-0000-0000-0000-000000000011',
    'تفسير القرآن العظيم (تفسير ابن كثير)',
    'دار طيبة للنشر والتوزيع',
    'الحافظ عماد الدين إسماعيل بن كثير (ت: 774هـ)',
    'TAFSEER',
    'أشهر وأوثق كتب التفسير بالمأثور، يفسر القرآن بالقرآن ثم بالسنة وآثار الصحابة والتابعين.',
    'https://quran.ksu.edu.sa/tafseer/katheer',
    'https://quran.ksu.edu.sa',
    'REFERENCE_WORK',
    'APPROVED',
    'VERIFIED',
    'الملكية العامة والتراث الإسلامي المحقق',
    '{"SEARCH": true, "DISPLAY_EXCERPT": true, "LINK": true, "INDEX": true, "STORE": true}'::jsonb,
    true, true, true, true, false, true,
    'العمدة في التفسير بالمأثور وتخريج الآثار.',
    now()
),
(
    '00000000-0000-0000-0000-000000000012',
    'مجموع الفتاوى لشيخ الإسلام ابن تيمية',
    'مجمع الملك فهد لطباعة المصحف / دار ابن حزم',
    'شيخ الإسلام أحمد بن عبد الحليم بن تيمية (ت: 728هـ)',
    'FIQH',
    'أشمل موسوعة فقهية وعقدية وتأصيلية محررة تتناول أبواب الفقه المقارن وأصول الاستدلال.',
    'https://shamela.ws/book/728',
    'https://shamela.ws/book/728',
    'REFERENCE_WORK',
    'APPROVED',
    'VERIFIED',
    'الملكية العامة المحققة',
    '{"SEARCH": true, "DISPLAY_EXCERPT": true, "LINK": true, "INDEX": true, "STORE": true}'::jsonb,
    true, true, true, true, false, true,
    'المرجع الشامل في الفقه المقارن وقواعد الاستدلال وبيان أسباب الخلاف.',
    now()
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    scientific_status = EXCLUDED.scientific_status,
    license_status = EXCLUDED.license_status,
    allowed_operations = EXCLUDED.allowed_operations,
    last_verified_at = now();
